#!/bin/bash

echo "🚀 Attendance System Deployment Helper"
echo "======================================"

echo ""
echo "📋 Prerequisites:"
echo "1. GitHub account"
echo "2. Render.com account (free)"
echo "3. MongoDB Atlas account (free)"
echo ""

echo "🔧 Step 1: Initialize Git Repository"
echo "Run these commands:"
echo "git init"
echo "git add ."
echo "git commit -m 'Initial commit'"
echo "git branch -M main"
echo ""

echo "📝 Step 2: Create GitHub Repository"
echo "1. Go to https://github.com/new"
echo "2. Name it: attendance-system"
echo "3. Make it public"
echo "4. Don't initialize with README"
echo ""

echo "🌐 Step 3: Set Up MongoDB Atlas"
echo "1. Go to https://www.mongodb.com/atlas"
echo "2. Create free account"
echo "3. Create new cluster"
echo "4. Get connection string"
echo ""

echo "🚀 Step 4: Deploy to Render"
echo "1. Go to https://render.com"
echo "2. Sign up with GitHub"
echo "3. Click 'New +' → 'Web Service'"
echo "4. Connect your repository"
echo "5. Configure:"
echo "   - Name: attendance-system"
echo "   - Environment: Node"
echo "   - Build Command: npm install"
echo "   - Start Command: npm start"
echo "6. Add Environment Variables:"
echo "   - MONGODB_URI: your Atlas connection string"
echo "   - NODE_ENV: production"
echo "   - PORT: 10000"
echo ""

echo "✅ After deployment, your app will be available at:"
echo "https://your-app-name.onrender.com"
echo ""

echo "📱 Test on mobile:"
echo "1. Generate QR code from deployed app"
echo "2. Scan with phone camera"
echo "3. Should open student scanner automatically!"
echo ""

echo "📖 For detailed instructions, see DEPLOYMENT.md"
echo ""
